apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eccube-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
