apiVersion: v1
kind: PersistentVolume
metadata:
  name: eccube-pv
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/eccube
