apiVersion: v1
kind: ConfigMap
metadata:
  name: eccube-config
data:
  APP_ENV: 'prod'
  APP_DEBUG: '0'
  DATABASE_URL: 'postgresql://postgres:password@eccube-pgsql:5432/eccube.db'
  DATABASE_SERVER_VERSION: '10'
  MAILER_URL: 'smtp://eccube-mail:1025'
  ECCUBE_ADMIN_USER: 'admin'
  ECCUBE_ADMIN_PASS: 'password'
  ECCUBE_AUTH_MAGIC: 'Myvpx7CecbURw9cF'
  ECCUBE_ADMIN_ROUTE: 'admin'
