apiVersion: apps/v1
kind: Deployment
metadata:
  name: eccube-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eccube-mail
  template:
    metadata:
      labels:
        app: eccube-mail
    spec:
      containers:
        - name: eccube-mail
          image: schickling/mailcatcher
          ports:
            - containerPort: 1080
            - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: eccube-mail
spec:
  type: NodePort
  selector:
    app: eccube-mail
  ports:
    - port: 1080
      targetPort: 1080
      name: mailer
    - port: 1025
      targetPort: 1025
      name: smtp
